name = "news-haikus-bot"
main = "src/index.ts"
compatibility_date = "2022-12-02"

[vars]
TWITTER_ACCESS_TOKEN = "Your Twitter access token"
TWITTER_ACCESS_TOKEN_SECRET = "Your Twitter access token secret"
TWITTER_API_KEY = "Your Twitter API key"
TWITTER_API_KEY_SECRET = "Your Twitter API key secret"
TWITTER_BEARER_TOKEN = "Your Twitter bearer token"
